---
- name: Setup Sublime Text repository and install Sublime Text
  hosts: all
  become: true

  tasks:
    - name: Download Sublime Text GPG key
      command: "curl -O https://download.sublimetext.com/sublimehq-pub.gpg"
      args:
        chdir: "/tmp"

    - name: Add Sublime Text GPG key
      command: "sudo pacman-key --add /tmp/sublimehq-pub.gpg"

    - name: Trust Sublime Text GPG key
      command: "sudo pacman-key --lsign-key 8A8F901A"

    - name: Remove downloaded GPG key file
      file:
        path: "/tmp/sublimehq-pub.gpg"
        state: absent

    - name: Add Sublime Text repository to pacman.conf
      blockinfile:
        path: "/etc/pacman.conf"
        block: |
          [sublime-text]
          Server = https://download.sublimetext.com/arch/stable/x86_64

    - name: Update package lists
      pacman:
        update_cache: yes

    - name: Install Sublime Text
      pacman:
        name: sublime-text
        state: present
